application:
  name: "Q&A with Gemini"
  layout: "wide"

gcp:
  project_id: "<UPDATE>"
  region: "us-central1"

llm:
  model_options:
    - "gemini-1.5-pro-001"
    - "gemini-1.5-flash-001"
    - "gemini-1.0-pro-vision-001"
  model_region: "us-central1"




